#! /bin/sh

# start input parser
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config presel_feedback_color "#444444"


bspc config border_width         2
#bspc config window_gap          12
bspc config window_gap           7

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc config top_padding          27

# bspc config click_to_focus none
bspc config pointer_modifier mod1

bspc rule -a discord desktop='^10'
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a floater state=floating
bspc rule -a feh state=floating
bspc rule -a Polybar state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Nm-connection-editor state=floating

feh --bg-fill ~/wallpapers/megumin1.jpeg

# make sure we see ourselves as LG3D for idea
wmname LG3D

# start compositor
# picom --experimental-backend &

# start notification manager
# dunst &

# start polybar
# /home/alex/.config/polybar/launch.sh &

# start discord
#discord &
